---

- name: sudo | add postgres user to the /etc/sudoers.d/postgres
  copy:
    dest: "/etc/sudoers.d/postgres"
    content: "postgres  ALL=(ALL)  NOPASSWD: ALL"
  tags: sudo

- import_tasks: ../tasks/pam_limits.yml